/**:
    ros__parameters:
        use_sim_time: true
        save_log: true
        log_filename: "EKF_log.csv"
        log_filepath: "./"

        ekf:
          frequency: 100.0
          max_iterations: 5
          acc_noise_covariance: 0.00001
          gyr_noise_covariance: 0.00001
          aero_noise_covariance: 0.0000001
          extrinsic_estim_enable: false